/* Graduation Invitation v3 - Static JS */
const CONFIG={graduationDate:"2026-08-02T07:30:00+07:00",storageKey:"pham-nhu-quynh-guestbook",giftAccessKey:"pham-nhu-quynh-gift-access"};
const pageText=window.INVITATION_CONFIG?.pageText||{};document.querySelectorAll("[data-config-text]").forEach(el=>{const key=el.dataset.configText;if(pageText[key])el.textContent=pageText[key]});document.querySelectorAll("[data-config-html]").forEach(el=>{const key=el.dataset.configHtml;if(pageText[key])el.innerHTML=pageText[key]});
const topbar=document.querySelector(".topbar"),heroName=document.querySelector(".hero-name");function updateToolbarState(){if(!topbar)return;topbar.classList.toggle("toolbar-solid",window.scrollY>60);if(heroName){const barHeight=topbar.offsetHeight||44;const nameRect=heroName.getBoundingClientRect();topbar.classList.toggle("toolbar-title-visible",nameRect.top<=barHeight+8)}}window.addEventListener("scroll",updateToolbarState,{passive:true});window.addEventListener("resize",updateToolbarState);updateToolbarState();
const themeBtn=document.getElementById("themeBtn"),themeKey="graduation-theme";function setTheme(theme){document.body.classList.toggle("dark-mode",theme==="dark");if(themeBtn){themeBtn.setAttribute("aria-pressed",theme==="dark"?"true":"false")}}setTheme(localStorage.getItem(themeKey)||"light");if(themeBtn){themeBtn.addEventListener("click",()=>{const next=document.body.classList.contains("dark-mode")?"light":"dark";localStorage.setItem(themeKey,next);setTheme(next)})}
const defaultGuests=[{name:"Nguyễn Minh Anh",message:"Chúc mừng Quỳnh nhé! Mong ngày tốt nghiệp của bạn thật nhiều niềm vui.",attend:"Sẽ đến",time:"Dữ liệu mẫu"},{name:"Trần Hoàng Nam",message:"Mình sẽ cố gắng sắp xếp thời gian để đến chúc mừng bạn.",attend:"Chưa chắc",time:"Dữ liệu mẫu"},{name:"Linh Chi",message:"Cuối cùng cũng đến ngày này rồi. Chúc mừng tân cử nhân Phạm Như Quỳnh!",attend:"Sẽ đến",time:"Dữ liệu mẫu"}];
function setupGiftGuard(){if(document.body.dataset.page!=="gift")return;const params=new URLSearchParams(window.location.search);const fromAdmin=params.get("from")==="admin";if(fromAdmin){sessionStorage.setItem(CONFIG.giftAccessKey,"1")}const allowed=sessionStorage.getItem(CONFIG.giftAccessKey)==="1";const guard=document.getElementById("giftGuard"),locked=document.getElementById("giftLocked"),open=document.getElementById("giftOpen");if(!allowed){if(guard)guard.classList.remove("hidden");if(locked)locked.classList.add("hidden");if(open)open.classList.add("hidden")}}setupGiftGuard();
const graduationDate=new Date(CONFIG.graduationDate).getTime();
function updateCountdown(){const now=Date.now();const distance=graduationDate-now;const safeDistance=Math.max(distance,0);const days=Math.floor(safeDistance/(1000*60*60*24));const hours=Math.floor((safeDistance/(1000*60*60))%24);const minutes=Math.floor((safeDistance/(1000*60))%60);const seconds=Math.floor((safeDistance/1000)%60);setText("days",days);setText("hours",hours);setText("minutes",minutes);setText("seconds",seconds);setText("giftDays",days);setText("giftHours",hours);setText("giftMinutes",minutes);setText("giftSeconds",seconds);if(distance<=0&&document.body.dataset.page==="gift"){const allowed=sessionStorage.getItem(CONFIG.giftAccessKey)==="1";const giftLocked=document.getElementById("giftLocked"),giftOpen=document.getElementById("giftOpen");if(allowed&&giftLocked&&giftOpen){giftLocked.classList.add("hidden");giftOpen.classList.remove("hidden")}}}
function setText(id,value){const el=document.getElementById(id);if(el){el.textContent=String(value).padStart(2,"0")}}setInterval(updateCountdown,1000);updateCountdown();
const musicBtn=document.getElementById("musicBtn"),bgMusic=document.getElementById("bgMusic");if(musicBtn&&bgMusic){let isPlaying=false;musicBtn.addEventListener("click",async()=>{try{if(!isPlaying){await bgMusic.play();musicBtn.textContent="Ⅱ";musicBtn.classList.add("playing");isPlaying=true}else{bgMusic.pause();musicBtn.textContent="♫";musicBtn.classList.remove("playing");isPlaying=false}}catch(error){alert("Chưa có file nhạc hoặc trình duyệt đang chặn phát nhạc. Hãy đặt file assets/music.mp3 rồi thử lại.")}})}
const menuBtn=document.getElementById("menuBtn"),closeMenuBtn=document.getElementById("closeMenuBtn"),sideMenu=document.getElementById("sideMenu"),menuBackdrop=document.getElementById("menuBackdrop");function openMenu(){if(!sideMenu||!menuBackdrop)return;sideMenu.classList.add("open");menuBackdrop.classList.add("open");document.body.classList.add("menu-open")}function closeMenu(){if(!sideMenu||!menuBackdrop)return;sideMenu.classList.remove("open");menuBackdrop.classList.remove("open");document.body.classList.remove("menu-open")}if(menuBtn)menuBtn.addEventListener("click",openMenu);if(closeMenuBtn)closeMenuBtn.addEventListener("click",closeMenu);if(menuBackdrop)menuBackdrop.addEventListener("click",closeMenu);document.querySelectorAll("[data-menu-link]").forEach(link=>{link.addEventListener("click",closeMenu)});
function getGuests(){const raw=localStorage.getItem(CONFIG.storageKey);if(!raw)return defaultGuests;try{const parsed=JSON.parse(raw);if(Array.isArray(parsed))return parsed;return defaultGuests}catch{return defaultGuests}}function saveGuests(guests){localStorage.setItem(CONFIG.storageKey,JSON.stringify(guests))}
const guestForm=document.getElementById("guestForm"),formThanks=document.getElementById("formThanks");if(guestForm){guestForm.addEventListener("submit",event=>{event.preventDefault();const name=document.getElementById("guestName").value.trim();const message=document.getElementById("guestMessage").value.trim();const attend=document.getElementById("guestAttend").value;if(!name||!message){alert("Bạn hãy nhập tên và lời nhắn trước khi gửi nhé.");return}const guests=getGuests();guests.unshift({name,message,attend,time:new Date().toLocaleString("vi-VN")});saveGuests(guests);guestForm.reset();if(formThanks){formThanks.style.display="block";setTimeout(()=>{formThanks.style.display="none"},4500)}})}
function fakeLogin(){const loginBox=document.getElementById("loginBox"),dashboardBox=document.getElementById("dashboardBox");if(loginBox&&dashboardBox){loginBox.classList.add("hidden");dashboardBox.classList.remove("hidden");sessionStorage.setItem(CONFIG.giftAccessKey,"1");renderAdminDashboard()}}function fakeLogout(){const loginBox=document.getElementById("loginBox"),dashboardBox=document.getElementById("dashboardBox");if(loginBox&&dashboardBox){dashboardBox.classList.add("hidden");loginBox.classList.remove("hidden")}}function renderAdminDashboard(){const guestList=document.getElementById("guestList");if(!guestList)return;const guests=getGuests();const total=guests.length;const yes=guests.filter(g=>g.attend==="Sẽ đến").length;const maybe=guests.filter(g=>g.attend==="Chưa chắc").length;const no=guests.filter(g=>g.attend==="Không đến được").length;setText("statTotal",total);setText("statYes",yes);setText("statMaybe",maybe);setText("statNo",no);if(guests.length===0){guestList.innerHTML=`<p class="empty-guest">Chưa có lời chúc nào.</p>`;return}guestList.innerHTML=guests.map(g=>`<article class="guest-item"><strong>${escapeHtml(g.name)}</strong><span>${escapeHtml(g.attend)}</span><p>${escapeHtml(g.message)}</p><div class="guest-time">${escapeHtml(g.time||"")}</div></article>`).join("")}
function clearGuestbook(){if(confirm("Bạn muốn xóa toàn bộ dữ liệu sổ lưu bút demo trong trình duyệt này?")){localStorage.removeItem(CONFIG.storageKey);renderAdminDashboard()}}function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
